box      = 'precise32'
url      = 'http://files.vagrantup.com/precise32.box'
domain   = 'btr3.com'


Vagrant.configure("2")  do |config|
  config.vm.box = box
  config.vm.box_url = url

  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
  end

	config.vm.define "jenkins" do |jenkins|
  	hostname="jenkins"
		jenkins.vm.host_name = hostname + '.' + domain
  	jenkins.vm.network "private_network", ip: "192.168.33.10"
  	jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
	end

  config.vm.define "slave1" do |slave1|
  	hostname="slave1"
		slave1.vm.host_name = hostname + '.' + domain
		slave1.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "slave2" do |slave2|
  	hostname="slave2"
		slave2.vm.host_name = hostname + '.' + domain
		slave2.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.define "slave3" do |slave3|
  	hostname="slave3"
		slave3.vm.host_name = hostname + '.' + domain
		slave3.vm.network "private_network", ip: "192.168.33.13"
  end

  config.vm.define "slave4" do |slave4|
  	hostname="slave4"
		slave4.vm.host_name = hostname + '.' + domain
		slave4.vm.network "private_network", ip: "192.168.33.14"
  end

end
